import { Roboto, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata = {
	title: "The Gist",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			{/* 			<body className={`${inter.className}, uppercase`}> */}
			<body className={inter.className}>{children}</body>
		</html>
	);
}
